version: '3.7'

services:
  mysql:
    container_name: mysql
    image: mysql:8.0.31-debian
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=Unpam
      - MYSQL_ROOT_PASSWORD=janganangel
      - MYSQL_USER=infra
      - MYSQL_PASSWORD=janganangel
  nginx:
    container_name: nginx
    image: nginx:alpine
    restart: always
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - 8080:80
    environment:
      - NGINX_PORT=80
